name=input("Nathan Amarante:")
empresa=input("Soirtec:")
qtde_funcionarios=int(input("Digite a qtde de funcionários: "))
mediamensalidaade=float(input("15.000:"))
print(name + "trabalha na empresa" + empresa)
print("possue:", qtde_funcionarios, "funcionarios.")
print("A media da mensalidade é: "+ str(mediamensalidaade))
print("==============Verifique os tipos de dados abaixo:==============")
print("O tipo de dados variavel [nome] é: ",type(name))
print("O tipo de dados variavel [empresa]é: ",type(empresa))
print("O tipo de dados variavel [qtde_funcionarios]é: ",type(qtde_funcionarios))
print("O tipo de dados variavel [mediamensalidade]é: ",type(mediamensalidaade))